import "../css/Post1.css";

function Post1() {
  return (
    <div>
      {/* Header Section */}
      <header className="about-header">
        <div className="framed-text">
          <h1>RAG</h1>
          <p>Retrieval Augmented Information like a Rag Doll</p>
          <br />
          <p>
            If you like business or bad jokes (or even better business AND bad
            jokes) you're at the right place.
          </p>
          <p>Read more for more info!</p>
        </div>
      </header>

    {/* Image Section */}
    <div className="post-image-container">
    <img src="/rag.jpg" alt="Post" className="post-image" />
    </div>

      {/* Content Section */}
      <div className="post-content">
        <p>This is some word content.</p>
      </div>
    </div>
  );
}

export default Post1;



// RAG [insert RAG doll picture here] stands for Retrieval Augmented Generation. 
// This is a technique used in Artificial Intelligence to improve the quality and relevance of responses generated by AI. Traditional language models generate responses based only on what they were trained on. This means they can’t access up-to-date information. Because of this they (being language models) may hallucinate facts or miss context.
// RAG is the solution to this by allowing the model to retrieve relevant documents from an external source (like a database or search engine). The model then uses them to generate more accurate responses.